In [10]:
import requests
import pandas as pd
from fetch_quarterly_equity_fmp import *
from fetch_marketcap_fmp import fetch_market_data_yearly

ticker = "MU"

api_key = "hT0gAk87j9xZx4PlBApvBqfVL5IahvgV"  # ← 사용자 제공 키
df_equity = fetch_quarterly_equity_fmp(ticker, api_key, start_date="2010-01-01")

market_data = fetch_market_data_yearly(ticker, api_key, start_year = 2010)

[FMP-MCAP-REQ] MU year=2010 url=https://financialmodelingprep.com/api/v3/historical-market-capitalization/MU apikey=***
[FMP-MCAP-RESP] MU year=2010 status=200
[FMP-MCAP-REQ] MU year=2011 url=https://financialmodelingprep.com/api/v3/historical-market-capitalization/MU apikey=***
[FMP-MCAP-RESP] MU year=2011 status=200
[FMP-MCAP-REQ] MU year=2025 url=https://financialmodelingprep.com/api/v3/historical-market-capitalization/MU apikey=***
[FMP-MCAP-RESP] MU year=2025 status=200
[FMP-MCAP-DONE] MU total_records=3982

In [12]:
pd.DataFrame(market_data)

     symbol        date     marketCap
0        MU  2010-12-31    7924562000
1        MU  2010-12-30    7805990000
2        MU  2010-12-29    7657775000
3        MU  2010-12-28    7667656000
4        MU  2010-12-27    7717061000
...     ...         ...           ...
3977     MU  2025-01-08  110842150000
3978     MU  2025-01-07  113629650000
3979     MU  2025-01-06  110674900000
3980     MU  2025-01-03  100205050000
3981     MU  2025-01-02   97372950000

[3982 rows x 3 columns]

In [3]:
df_pbr

         date symbol       pbr period calendarYear fiscalDateEnding
0  2010-09-02     MU  0.755814     FY         2010             None
1  2011-09-01     MU  0.669554     FY         2011             None
2  2012-08-30     MU  0.795535     FY         2012             None
3  2013-08-29     MU  1.516568     FY         2013             None
4  2014-08-28     MU  3.228911     FY         2014             None
5  2015-09-03     MU  1.442960     FY         2015             None
6  2016-09-01     MU  1.408094     FY         2016             None
7  2017-08-31     MU  1.869681     FY         2017             None
8  2018-08-30     MU  2.006335     FY         2018             None
9  2019-08-29     MU  1.386873     FY         2019             None
10 2020-09-03     MU  1.318758     FY         2020             None
11 2021-09-02     MU  1.886254     FY         2021             None
12 2022-09-01     MU  1.276950     FY         2022             None
13 2023-08-31     MU  1.732648     FY         2023             None
14 2024-08-29     MU  2.339963     FY         2024             None
15 2025-08-28     MU  2.513653     FY         2025             None